try {
    throw "exception!"; // exception 만들기
}
catch (e) {
    console.log(e); // 모든 exception을 출력
}
